"""Compile mathematical expression strings into callable PyTorch update rules.

This module takes free-form math expressions (generated by an LLM or hand-written)
and compiles them into step functions compatible with the Lenia simulation loop.

The compiled function signature is:  step_fn(state_tensor) -> new_state_tensor

Safety:
  - Uses a restricted eval namespace (no builtins, no file I/O)
  - Per-step timeout via signal (Unix only)
  - All exceptions caught and re-raised as CompilationError or RuntimeError
"""

from __future__ import annotations

import math
import signal
from typing import Callable, Optional

import torch
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class CompilationError(Exception):
    """Raised when an expression string cannot be compiled."""
    pass


class StepTimeoutError(Exception):
    """Raised when a single simulation step exceeds the time limit."""
    pass


# ---------------------------------------------------------------------------
# Helper operations available inside expressions
# ---------------------------------------------------------------------------

def _build_gaussian_kernel(resolution: int, radius: int = 13) -> torch.Tensor:
    """Build a normalised Gaussian convolution kernel, FFT-ready.

    Returns the FFT2 of the kernel (complex tensor of shape [resolution, resolution]).
    """
    R = resolution
    mid = R // 2
    y = torch.arange(R, dtype=torch.float32) - mid
    x = torch.arange(R, dtype=torch.float32) - mid
    yy, xx = torch.meshgrid(y, x, indexing="ij")
    dist = torch.sqrt(xx ** 2 + yy ** 2) / max(radius, 1.0)

    # Gaussian profile with compact support
    raw = torch.exp(-((dist * 1.0 - 1.0).pow(2)) / (2 * 0.15 ** 2))
    raw = raw * (dist <= 1.0).float()

    # Normalise
    total = raw.sum()
    if total > 0:
        raw = raw / total

    # Shift for FFT convolution (centre at 0,0)
    kernel_shifted = torch.roll(raw, shifts=(-mid, -mid), dims=(0, 1))
    return torch.fft.fft2(kernel_shifted)


def _make_conv_fn(kernel_fft: torch.Tensor):
    """Return a function that convolves a 2D state with the pre-computed kernel."""

    def conv(A: torch.Tensor) -> torch.Tensor:
        state_fft = torch.fft.fft2(A)
        return torch.fft.ifft2(state_fft * kernel_fft).real

    return conv


def _laplacian(A: torch.Tensor) -> torch.Tensor:
    """Discrete Laplacian using a 3x3 stencil with periodic boundary."""
    Ap = A.unsqueeze(0).unsqueeze(0)  # [1, 1, H, W]
    Ap = F.pad(Ap, (1, 1, 1, 1), mode="circular")
    kernel = torch.tensor(
        [[0.0, 1.0, 0.0], [1.0, -4.0, 1.0], [0.0, 1.0, 0.0]],
        dtype=A.dtype, device=A.device,
    ).unsqueeze(0).unsqueeze(0)
    result = F.conv2d(Ap, kernel)
    return result.squeeze(0).squeeze(0)


def _gradient_x(A: torch.Tensor) -> torch.Tensor:
    """Horizontal gradient (central difference) with periodic boundary."""
    return (torch.roll(A, -1, dims=1) - torch.roll(A, 1, dims=1)) / 2.0


def _gradient_y(A: torch.Tensor) -> torch.Tensor:
    """Vertical gradient (central difference) with periodic boundary."""
    return (torch.roll(A, -1, dims=0) - torch.roll(A, 1, dims=0)) / 2.0


def _clip(x, lo=0.0, hi=1.0):
    """Clip tensor values to [lo, hi]."""
    if isinstance(x, torch.Tensor):
        return x.clamp(min=float(lo), max=float(hi))
    return max(lo, min(hi, x))


def _threshold(x: torch.Tensor, t: float = 0.5) -> torch.Tensor:
    """Hard threshold: returns 1 where x > t, else 0."""
    return (x > t).float()


def _safe_sqrt(x):
    """Square root with clamped input to avoid NaN."""
    if isinstance(x, torch.Tensor):
        return torch.sqrt(x.clamp(min=0.0))
    return math.sqrt(max(0.0, x))


def _safe_log(x):
    """Logarithm with clamped input to avoid -inf/NaN."""
    if isinstance(x, torch.Tensor):
        return torch.log(x.clamp(min=1e-10))
    return math.log(max(x, 1e-10))


def _safe_div(a, b):
    """Division with small epsilon to avoid division by zero."""
    if isinstance(b, torch.Tensor):
        return a / (b + 1e-10)
    if isinstance(a, torch.Tensor):
        return a / (b + 1e-10)
    return a / (b + 1e-10)


def _torch_max(a, b):
    """Element-wise maximum that handles mixed tensor/scalar."""
    if isinstance(a, torch.Tensor) and isinstance(b, torch.Tensor):
        return torch.maximum(a, b)
    if isinstance(a, torch.Tensor):
        return torch.clamp(a, min=float(b))
    if isinstance(b, torch.Tensor):
        return torch.clamp(b, min=float(a))
    return max(a, b)


def _torch_min(a, b):
    """Element-wise minimum that handles mixed tensor/scalar."""
    if isinstance(a, torch.Tensor) and isinstance(b, torch.Tensor):
        return torch.minimum(a, b)
    if isinstance(a, torch.Tensor):
        return torch.clamp(a, max=float(b))
    if isinstance(b, torch.Tensor):
        return torch.clamp(b, max=float(a))
    return min(a, b)


# ---------------------------------------------------------------------------
# High-level operations for LLM (Round 6+)
# ---------------------------------------------------------------------------

def _conserve(A: torch.Tensor, B: torch.Tensor, target: float = 1.0) -> tuple:
    """Normalize A and B so that A + B = target locally. Returns (A_new, B_new)."""
    total = A + B + 1e-10
    scale = target / total
    return (A * scale).clamp(0, 1), (B * scale).clamp(0, 1)


def _conserve_a(A: torch.Tensor, B: torch.Tensor, target: float = 1.0) -> torch.Tensor:
    """Return conserved A field (A + B normalized to target)."""
    total = A + B + 1e-10
    return (A * target / total).clamp(0, 1)


def _conserve_b(A: torch.Tensor, B: torch.Tensor, target: float = 1.0) -> torch.Tensor:
    """Return conserved B field."""
    total = A + B + 1e-10
    return (B * target / total).clamp(0, 1)


def _rotate_cw(F: torch.Tensor) -> torch.Tensor:
    """Clockwise rotation by 90 degrees — chiral operation."""
    gx = (torch.roll(F, -1, dims=1) - torch.roll(F, 1, dims=1)) / 2.0
    gy = (torch.roll(F, -1, dims=0) - torch.roll(F, 1, dims=0)) / 2.0
    return torch.sqrt(gx**2 + gy**2 + 1e-10)


def _rotate_ccw(F: torch.Tensor) -> torch.Tensor:
    """Counter-clockwise rotation — opposite chirality."""
    gx = (torch.roll(F, 1, dims=1) - torch.roll(F, -1, dims=1)) / 2.0
    gy = (torch.roll(F, 1, dims=0) - torch.roll(F, -1, dims=0)) / 2.0
    return torch.sqrt(gx**2 + gy**2 + 1e-10)


def _curl(F: torch.Tensor) -> torch.Tensor:
    """Curl (vorticity) of a scalar field — detects rotational structure."""
    gx = (torch.roll(F, -1, dims=1) - torch.roll(F, 1, dims=1)) / 2.0
    gy = (torch.roll(F, -1, dims=0) - torch.roll(F, 1, dims=0)) / 2.0
    # curl = d(gy)/dx - d(gx)/dy
    dgydx = (torch.roll(gy, -1, dims=1) - torch.roll(gy, 1, dims=1)) / 2.0
    dgxdy = (torch.roll(gx, -1, dims=0) - torch.roll(gx, 1, dims=0)) / 2.0
    return dgydx - dgxdy


def _global_mean(F: torch.Tensor) -> torch.Tensor:
    """Global mean — for conservation-type expressions."""
    return torch.full_like(F, F.mean().item())


def _compete(A: torch.Tensor, B: torch.Tensor, strength: float = 1.0) -> torch.Tensor:
    """Competition term: A's growth is suppressed where B is strong."""
    return A * (1.0 - strength * B).clamp(min=0.0)


# ---------------------------------------------------------------------------
# Expression compilation
# ---------------------------------------------------------------------------

def _build_namespace(
    resolution: int,
    kernel_fft: torch.Tensor,
    kernel_fft_b: Optional[torch.Tensor] = None,
) -> dict:
    """Build the restricted namespace for eval().

    Only safe math/torch operations are exposed.

    Parameters
    ----------
    resolution : int
        Grid resolution.
    kernel_fft : torch.Tensor
        FFT of the convolution kernel (used for field A, and as default conv).
    kernel_fft_b : torch.Tensor, optional
        FFT of a second convolution kernel for field B. If None, uses same kernel as A.
    """
    conv_fn = _make_conv_fn(kernel_fft)
    conv_b_fn = _make_conv_fn(kernel_fft_b if kernel_fft_b is not None else kernel_fft)

    namespace = {
        # No builtins at all
        "__builtins__": {},

        # Spatial operations (default operates on whatever is passed)
        "conv": conv_fn,
        "conv_b": conv_b_fn,
        "laplacian": _laplacian,
        "gradient_x": _gradient_x,
        "gradient_y": _gradient_y,

        # Element-wise math (torch)
        "sin": torch.sin,
        "cos": torch.cos,
        "tanh": torch.tanh,
        "exp": torch.exp,
        "abs": torch.abs,
        "sqrt": _safe_sqrt,
        "log": _safe_log,
        "sigmoid": torch.sigmoid,
        "sign": torch.sign,

        # Utility
        "clip": _clip,
        "threshold": _threshold,
        "max": _torch_max,
        "min": _torch_min,
        "mean": lambda x: x.mean() if isinstance(x, torch.Tensor) else x,

        # Constants
        "pi": math.pi,
        "e": math.e,

        # High-level operations (Round 6+)
        "conserve_a": _conserve_a,  # conserve_a(A, B) -> normalized A so A+B=1
        "conserve_b": _conserve_b,  # conserve_b(A, B) -> normalized B so A+B=1
        "rotate_cw": _rotate_cw,    # clockwise chirality
        "rotate_ccw": _rotate_ccw,  # counter-clockwise chirality
        "curl": _curl,              # vorticity / rotational structure
        "global_mean": _global_mean, # global average (for conservation)
        "compete": _compete,        # compete(A, B) -> A suppressed where B is strong
    }
    return namespace


def compile_expression(
    expr_str: str,
    resolution: int = 64,
    kernel_radius: int = 13,
    step_timeout: float = 5.0,
) -> Callable[[torch.Tensor], torch.Tensor]:
    """Compile a mathematical expression string into a callable step function.

    Parameters
    ----------
    expr_str : str
        A mathematical expression using available operations.
        The variable ``A`` represents the current 2D state tensor.
        Example: "clip(A + 0.1 * (2 * exp(-((conv(A) - 0.15) / 0.02)**2) - 1), 0, 1)"
    resolution : int
        Grid resolution (NxN). Determines kernel size.
    kernel_radius : int
        Radius of the default Gaussian convolution kernel.
    step_timeout : float
        Maximum seconds allowed per step call.

    Returns
    -------
    callable
        step_fn(state_tensor) -> new_state_tensor

    Raises
    ------
    CompilationError
        If the expression cannot be parsed or compiled.
    """
    # Validate expression string (basic safety checks)
    expr_str = expr_str.strip()
    if not expr_str:
        raise CompilationError("Empty expression string")

    # Block dangerous patterns
    dangerous_patterns = [
        "import", "exec", "open(", "file(", "__", "os.", "sys.",
        "subprocess", "getattr", "setattr", "delattr", "globals", "locals",
        "compile(", "breakpoint", "input(",
    ]
    expr_lower = expr_str.lower()
    for pattern in dangerous_patterns:
        if pattern in expr_lower:
            raise CompilationError(f"Expression contains forbidden pattern: '{pattern}'")

    # Pre-compile the expression to catch syntax errors early
    try:
        code = compile(expr_str, "<expression>", "eval")
    except SyntaxError as exc:
        raise CompilationError(f"Syntax error in expression: {exc}") from exc

    # Build kernel and namespace
    kernel_fft = _build_gaussian_kernel(resolution, kernel_radius)
    namespace = _build_namespace(resolution, kernel_fft)

    def step_fn(state: torch.Tensor) -> torch.Tensor:
        """Execute one step of the compiled update rule."""
        nonlocal kernel_fft, namespace

        # Move kernel to same device as state if needed
        if state.device != kernel_fft.device:
            kernel_fft = kernel_fft.to(state.device)
            namespace = _build_namespace(resolution, kernel_fft)

        # Set up the state variable
        local_ns = dict(namespace)
        local_ns["A"] = state

        # Set timeout (Unix only)
        use_timeout = hasattr(signal, "SIGALRM") and step_timeout > 0

        def _timeout_handler(signum, frame):
            raise StepTimeoutError(
                f"Step exceeded {step_timeout}s timeout for expression: {expr_str[:100]}..."
            )

        if use_timeout:
            old_handler = signal.signal(signal.SIGALRM, _timeout_handler)
            signal.alarm(int(math.ceil(step_timeout)))

        try:
            result = eval(code, local_ns)
        except StepTimeoutError:
            raise
        except Exception as exc:
            raise RuntimeError(
                f"Error evaluating expression '{expr_str[:100]}...': {exc}"
            ) from exc
        finally:
            if use_timeout:
                signal.alarm(0)  # Cancel alarm
                signal.signal(signal.SIGALRM, old_handler)

        # Ensure result is a tensor of the right shape
        if isinstance(result, (int, float)):
            result = torch.full_like(state, float(result))
        if not isinstance(result, torch.Tensor):
            raise RuntimeError(
                f"Expression did not return a tensor, got {type(result).__name__}"
            )
        if result.shape != state.shape:
            raise RuntimeError(
                f"Expression returned wrong shape: expected {state.shape}, got {result.shape}"
            )

        # Final safety clamp to [0, 1]
        return result.clamp(0.0, 1.0)

    # Quick validation: test with a small random state
    try:
        test_state = torch.rand(resolution, resolution)
        test_result = step_fn(test_state)
        assert test_result.shape == test_state.shape, "Shape mismatch in validation"
        assert test_result.min() >= 0.0 and test_result.max() <= 1.0, "Range violation"
    except StepTimeoutError:
        raise CompilationError(
            f"Expression timed out during validation: {expr_str[:100]}"
        )
    except Exception as exc:
        raise CompilationError(f"Expression failed validation: {exc}") from exc

    return step_fn


# ---------------------------------------------------------------------------
# Convenience: run a full simulation with a compiled expression
# ---------------------------------------------------------------------------

def _center_blob_init(resolution: int, blob_radius: float = 0.15,
                       device: str = "cpu", intensity: float = 0.5) -> torch.Tensor:
    """Initialize with a circular random patch in the center, rest zero.

    This encourages localized creature formation by giving a compact
    starting seed rather than filling the whole centre quarter.
    """
    R = resolution
    state = torch.zeros(R, R, device=device, dtype=torch.float32)
    cx, cy = R // 2, R // 2
    r = int(R * blob_radius)
    y, x = torch.meshgrid(
        torch.arange(R, device=device),
        torch.arange(R, device=device),
        indexing="ij",
    )
    mask = ((x - cx) ** 2 + (y - cy) ** 2) < r ** 2
    state[mask] = torch.rand(int(mask.sum().item()), device=device) * intensity
    return state


def _random_quarter_init(resolution: int, device: str = "cpu",
                          intensity: float = 1.0) -> torch.Tensor:
    """Original initialization: random values in centre quarter."""
    R = resolution
    state = torch.zeros(R, R, device=device, dtype=torch.float32)
    q = R // 4
    state[q: 3 * q, q: 3 * q] = torch.rand(
        2 * q, 2 * q, device=device, dtype=torch.float32
    ) * intensity
    return state


def run_expression(
    expr_str: str,
    resolution: int = 64,
    steps: int = 2000,
    record_interval: int = 10,
    kernel_radius: int = 13,
    device: str = "cpu",
    init_mode: str = "random_quarter",
) -> list[torch.Tensor]:
    """Compile an expression and run a full simulation.

    Parameters
    ----------
    expr_str : str
        Mathematical expression for the update rule.
    resolution : int
        Grid size NxN.
    steps : int
        Number of simulation steps.
    record_interval : int
        Record state every N steps.
    kernel_radius : int
        Convolution kernel radius.
    device : str
        PyTorch device.
    init_mode : str
        "random_quarter" (original) or "center_blob" (for localized creature search).

    Returns
    -------
    list[torch.Tensor]
        State history (detached CPU tensors).
    """
    step_fn = compile_expression(expr_str, resolution, kernel_radius)

    # Initialize based on mode
    if init_mode == "center_blob":
        state = _center_blob_init(resolution, blob_radius=0.15, device=device)
    else:
        state = _random_quarter_init(resolution, device=device)

    history: list[torch.Tensor] = []
    for i in range(steps):
        try:
            state = step_fn(state)
        except (StepTimeoutError, RuntimeError):
            # Record what we have and bail
            history.append(state.detach().cpu().clone())
            break

        if i % record_interval == 0 or i == steps - 1:
            history.append(state.detach().cpu().clone())

    return history



# ---------------------------------------------------------------------------
# Dual-field (coupled A and B) expression compilation
# ---------------------------------------------------------------------------

def compile_dual_expression(
    expr_a: str,
    expr_b: str,
    resolution: int = 64,
    kernel_radius: int = 13,
    step_timeout: float = 5.0,
) -> Callable[[torch.Tensor, torch.Tensor], tuple[torch.Tensor, torch.Tensor]]:
    """Compile two coupled expressions (one for each field) into a step function.

    Parameters
    ----------
    expr_a : str
        Update rule for field A. Can reference both A and B.
    expr_b : str
        Update rule for field B. Can reference both A and B.
    resolution : int
        Grid resolution (NxN).
    kernel_radius : int
        Radius of the default Gaussian convolution kernel.
    step_timeout : float
        Maximum seconds allowed per step call.

    Returns
    -------
    callable
        step_fn(state_a, state_b) -> (new_state_a, new_state_b)

    Raises
    ------
    CompilationError
        If either expression cannot be parsed or compiled.
    """
    for label, expr_str in [("A", expr_a), ("B", expr_b)]:
        expr_str = expr_str.strip()
        if not expr_str:
            raise CompilationError(f"Empty expression string for field {label}")

        # Block dangerous patterns
        dangerous_patterns = [
            "import", "exec", "open(", "file(", "__", "os.", "sys.",
            "subprocess", "getattr", "setattr", "delattr", "globals", "locals",
            "compile(", "breakpoint", "input(",
        ]
        expr_lower = expr_str.lower()
        for pattern in dangerous_patterns:
            if pattern in expr_lower:
                raise CompilationError(
                    f"Expression for field {label} contains forbidden pattern: '{pattern}'"
                )

    # Pre-compile both expressions
    try:
        code_a = compile(expr_a.strip(), "<expr_a>", "eval")
    except SyntaxError as exc:
        raise CompilationError(f"Syntax error in expression A: {exc}") from exc

    try:
        code_b = compile(expr_b.strip(), "<expr_b>", "eval")
    except SyntaxError as exc:
        raise CompilationError(f"Syntax error in expression B: {exc}") from exc

    # Build kernel and namespace
    kernel_fft = _build_gaussian_kernel(resolution, kernel_radius)
    namespace = _build_namespace(resolution, kernel_fft)

    def step_fn(
        state_a: torch.Tensor, state_b: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Execute one step of the coupled dual-field update rule."""
        nonlocal kernel_fft, namespace

        # Move kernel to same device as state if needed
        if state_a.device != kernel_fft.device:
            kernel_fft = kernel_fft.to(state_a.device)
            namespace = _build_namespace(resolution, kernel_fft)

        # Set up the state variables: both A and B available in namespace
        local_ns = dict(namespace)
        local_ns["A"] = state_a
        local_ns["B"] = state_b

        # Set timeout (Unix only)
        use_timeout = hasattr(signal, "SIGALRM") and step_timeout > 0

        def _timeout_handler(signum, frame):
            raise StepTimeoutError(
                f"Dual step exceeded {step_timeout}s timeout"
            )

        if use_timeout:
            old_handler = signal.signal(signal.SIGALRM, _timeout_handler)
            signal.alarm(int(math.ceil(step_timeout)))

        try:
            result_a = eval(code_a, local_ns)
            result_b = eval(code_b, local_ns)
        except StepTimeoutError:
            raise
        except Exception as exc:
            raise RuntimeError(
                f"Error evaluating dual expression: {exc}"
            ) from exc
        finally:
            if use_timeout:
                signal.alarm(0)
                signal.signal(signal.SIGALRM, old_handler)

        # Ensure results are tensors of the right shape
        for label, result, state in [("A", result_a, state_a), ("B", result_b, state_b)]:
            if isinstance(result, (int, float)):
                if label == "A":
                    result_a = torch.full_like(state, float(result))
                else:
                    result_b = torch.full_like(state, float(result))
                result = result_a if label == "A" else result_b
            if not isinstance(result, torch.Tensor):
                raise RuntimeError(
                    f"Expression for field {label} did not return a tensor, "
                    f"got {type(result).__name__}"
                )
            if result.shape != state.shape:
                raise RuntimeError(
                    f"Expression for field {label} returned wrong shape: "
                    f"expected {state.shape}, got {result.shape}"
                )

        # Final safety clamp to [0, 1]
        return result_a.clamp(0.0, 1.0), result_b.clamp(0.0, 1.0)

    # Quick validation: test with small random states
    try:
        test_a = torch.rand(resolution, resolution)
        test_b = torch.rand(resolution, resolution)
        out_a, out_b = step_fn(test_a, test_b)
        assert out_a.shape == test_a.shape, "Shape mismatch for field A in validation"
        assert out_b.shape == test_b.shape, "Shape mismatch for field B in validation"
        assert out_a.min() >= 0.0 and out_a.max() <= 1.0, "Range violation for field A"
        assert out_b.min() >= 0.0 and out_b.max() <= 1.0, "Range violation for field B"
    except StepTimeoutError:
        raise CompilationError(
            f"Dual expression timed out during validation"
        )
    except Exception as exc:
        raise CompilationError(f"Dual expression failed validation: {exc}") from exc

    return step_fn


def run_dual_expression(
    expr_a: str,
    expr_b: str,
    resolution: int = 64,
    steps: int = 2000,
    record_interval: int = 10,
    kernel_radius: int = 13,
    device: str = "cpu",
    init_mode: str = "random_quarter",
) -> list[torch.Tensor]:
    """Compile two coupled expressions and run a full dual-field simulation.

    Parameters
    ----------
    expr_a : str
        Update rule for field A (can reference both A and B).
    expr_b : str
        Update rule for field B (can reference both A and B).
    resolution : int
        Grid size NxN.
    steps : int
        Number of simulation steps.
    record_interval : int
        Record state every N steps.
    kernel_radius : int
        Convolution kernel radius.
    device : str
        PyTorch device.

    Returns
    -------
    list[torch.Tensor]
        State history of combined fields (detached CPU tensors).
        Each tensor is max(A, B) clipped to [0, 1], for evaluator compatibility.
    """
    step_fn = compile_dual_expression(
        expr_a, expr_b, resolution, kernel_radius
    )

    R = resolution

    # Initialize based on mode
    if init_mode == "center_blob":
        state_a = _center_blob_init(R, blob_radius=0.15, device=device, intensity=0.5)
        state_b = _center_blob_init(R, blob_radius=0.12, device=device, intensity=0.3)
    else:
        state_a = _random_quarter_init(R, device=device, intensity=1.0)
        state_b = _random_quarter_init(R, device=device, intensity=0.5)

    history: list[torch.Tensor] = []
    for i in range(steps):
        try:
            state_a, state_b = step_fn(state_a, state_b)
        except (StepTimeoutError, RuntimeError):
            # Record what we have and bail
            combined = torch.maximum(state_a, state_b).clamp(0.0, 1.0)
            history.append(combined.detach().cpu().clone())
            break

        if i % record_interval == 0 or i == steps - 1:
            # Combine A and B into a single tensor for evaluator compatibility
            combined = torch.maximum(state_a, state_b).clamp(0.0, 1.0)
            history.append(combined.detach().cpu().clone())

    return history
